on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.3
          run_install: true
      - name: build
        run: |
          pnpm run build
          tar -czvf dist.tgz ./dist
      - name: Generate release note
        run: node ./.github/workflows/release-notes.mjs
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: release-note.md
          files: dist.tgz
